ktor:
  application:
    modules:
      - com.int531.ApplicationKt.module
  deployment:
    port: 8080

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:3306}
  name: ${DB_NAME:int531}
  user: ${DB_USER:root}
  password: ${DB_PASSWORD:rootpassword}
